Public Function HttpStatusString(Status As Integer) As String
    If Status = 100 Then
		HttpStatusString = "Continue"
    ElseIf Status = 101 Then
		HttpStatusString = "Switching Protocols"
    ElseIf Status = 102 Then
		HttpStatusString = "Processing"
    ElseIf Status = 200 Then
		HttpStatusString = "OK"
    ElseIf Status = 201 Then
		HttpStatusString = "Created"
    ElseIf Status = 202 Then
		HttpStatusString = "Accepted"
    ElseIf Status = 203 Then
		HttpStatusString = "Non-authoritative Information"
    ElseIf Status = 204 Then
		HttpStatusString = "No Content"
    ElseIf Status = 205 Then
		HttpStatusString = "Reset Content"
    ElseIf Status = 206 Then
		HttpStatusString = "Partial Content"
    ElseIf Status = 207 Then
		HttpStatusString = "Multi-Status"
    ElseIf Status = 208 Then
		HttpStatusString = "Already Reported"
    ElseIf Status = 226 Then
		HttpStatusString = "IM Used"
    ElseIf Status = 300 Then
		HttpStatusString = "Multiple Choices"
    ElseIf Status = 301 Then
		HttpStatusString = "Moved Permanently"
    ElseIf Status = 302 Then
		HttpStatusString = "Found"
    ElseIf Status = 303 Then
		HttpStatusString = "See Other"
    ElseIf Status = 304 Then
		HttpStatusString = "Not Modified"
    ElseIf Status = 305 Then
		HttpStatusString = "Use Proxy"
    ElseIf Status = 307 Then
		HttpStatusString = "Temporary Redirect"
    ElseIf Status = 308 Then
		HttpStatusString = "Permanent Redirect"
    ElseIf Status = 400 Then
		HttpStatusString = "Bad Request"
    ElseIf Status = 401 Then
		HttpStatusString = "Unauthorized"
    ElseIf Status = 402 Then
		HttpStatusString = "Payment Required"
    ElseIf Status = 403 Then
		HttpStatusString = "Forbidden"
    ElseIf Status = 404 Then
		HttpStatusString = "Not Found"
    ElseIf Status = 405 Then
		HttpStatusString = "Method Not Allowed"
    ElseIf Status = 406 Then
		HttpStatusString = "Not Acceptable"
    ElseIf Status = 407 Then
		HttpStatusString = "Proxy Authentication Required"
    ElseIf Status = 408 Then
		HttpStatusString = "Request Timeout"
    ElseIf Status = 409 Then
		HttpStatusString = "Conflict"
    ElseIf Status = 410 Then
		HttpStatusString = "Gone"
    ElseIf Status = 411 Then
		HttpStatusString = "Length Required"
    ElseIf Status = 412 Then
		HttpStatusString = "Precondition Failed"
    ElseIf Status = 413 Then
		HttpStatusString = "Payload Too Large"
    ElseIf Status = 414 Then
		HttpStatusString = "Request-URI Too Long"
    ElseIf Status = 415 Then
		HttpStatusString = "Unsupported Media Type"
    ElseIf Status = 416 Then
		HttpStatusString = "Requested Range Not Satisfiable"
    ElseIf Status = 417 Then
		HttpStatusString = "Expectation Failed"
    ElseIf Status = 418 Then
		HttpStatusString = "I'm a teapot"
    ElseIf Status = 421 Then
		HttpStatusString = "Misdirected Request"
    ElseIf Status = 422 Then
		HttpStatusString = "Unprocessable Entity"
    ElseIf Status = 423 Then
		HttpStatusString = "Locked"
    ElseIf Status = 424 Then
		HttpStatusString = "Failed Dependency"
    ElseIf Status = 426 Then
		HttpStatusString = "Upgrade Required"
    ElseIf Status = 428 Then
		HttpStatusString = "Precondition Required"
    ElseIf Status = 429 Then
		HttpStatusString = "Too Many Requests"
    ElseIf Status = 431 Then
		HttpStatusString = "Request Header Fields Too Large"
    ElseIf Status = 444 Then
		HttpStatusString = "Connection Closed Without Response"
    ElseIf Status = 451 Then
		HttpStatusString = "Unavailable For Legal Reasons"
    ElseIf Status = 499 Then
		HttpStatusString = "Client Closed Request"
    ElseIf Status = 500 Then
		HttpStatusString = "Internal Server Error"
    ElseIf Status = 501 Then
		HttpStatusString = "Not Implemented"
    ElseIf Status = 502 Then
		HttpStatusString = "Bad Gateway"
    ElseIf Status = 503 Then
		HttpStatusString = "Service Unavailable"
    ElseIf Status = 504 Then
		HttpStatusString = "Gateway Timeout"
    ElseIf Status = 505 Then
		HttpStatusString = "HTTP Version Not Supported"
    ElseIf Status = 506 Then
		HttpStatusString = "Variant Also Negotiates"
    ElseIf Status = 507 Then
		HttpStatusString = "Insufficient Storage"
    ElseIf Status = 508 Then
		HttpStatusString = "Loop Detected"
    ElseIf Status = 510 Then
		HttpStatusString = "Not Extended"
    ElseIf Status = 511 Then
		HttpStatusString = "Network Authentication Required"
    ElseIf Status = 599 Then
		HttpStatusString = "Network Connect Timeout Error"
    Else
        HttpStatusString = "What The HECK is this"
    End If
End Function