Attribute VB_Name = "HttpStatusCode"
Option Private Module ' To hide the init sub in the macro list
Public HttpStatusMessages As Object

Sub InitializeHttpStatusDictionary()
    Set HttpStatusMessages = CreateObject("Scripting.Dictionary")
    HttpStatusMessages.Add 100, "Continue"
    HttpStatusMessages.Add 101, "Switching Protocols"
    HttpStatusMessages.Add 102, "Processing"
    HttpStatusMessages.Add 200, "OK"
    HttpStatusMessages.Add 201, "Created"
    HttpStatusMessages.Add 202, "Accepted"
    HttpStatusMessages.Add 203, "Non-authoritative Information"
    HttpStatusMessages.Add 204, "No Content"
    HttpStatusMessages.Add 205, "Reset Content"
    HttpStatusMessages.Add 206, "Partial Content"
    HttpStatusMessages.Add 207, "Multi-Status"
    HttpStatusMessages.Add 208, "Already Reported"
    HttpStatusMessages.Add 226, "IM Used"
    HttpStatusMessages.Add 300, "Multiple Choices"
    HttpStatusMessages.Add 301, "Moved Permanently"
    HttpStatusMessages.Add 302, "Found"
    HttpStatusMessages.Add 303, "See Other"
    HttpStatusMessages.Add 304, "Not Modified"
    HttpStatusMessages.Add 305, "Use Proxy"
    HttpStatusMessages.Add 307, "Temporary Redirect"
    HttpStatusMessages.Add 308, "Permanent Redirect"
    HttpStatusMessages.Add 400, "Bad Request"
    HttpStatusMessages.Add 401, "Unauthorized"
    HttpStatusMessages.Add 402, "Payment Required"
    HttpStatusMessages.Add 403, "Forbidden"
    HttpStatusMessages.Add 404, "Not Found"
    HttpStatusMessages.Add 405, "Method Not Allowed"
    HttpStatusMessages.Add 406, "Not Acceptable"
    HttpStatusMessages.Add 407, "Proxy Authentication Required"
    HttpStatusMessages.Add 408, "Request Timeout"
    HttpStatusMessages.Add 409, "Conflict"
    HttpStatusMessages.Add 410, "Gone"
    HttpStatusMessages.Add 411, "Length Required"
    HttpStatusMessages.Add 412, "Precondition Failed"
    HttpStatusMessages.Add 413, "Payload Too Large"
    HttpStatusMessages.Add 414, "Request-URI Too Long"
    HttpStatusMessages.Add 415, "Unsupported Media Type"
    HttpStatusMessages.Add 416, "Requested Range Not Satisfiable"
    HttpStatusMessages.Add 417, "Expectation Failed"
    HttpStatusMessages.Add 418, "I'm a teapot"
    HttpStatusMessages.Add 421, "Misdirected Request"
    HttpStatusMessages.Add 422, "Unprocessable Entity"
    HttpStatusMessages.Add 423, "Locked"
    HttpStatusMessages.Add 424, "Failed Dependency"
    HttpStatusMessages.Add 426, "Upgrade Required"
    HttpStatusMessages.Add 428, "Precondition Required"
    HttpStatusMessages.Add 429, "Too Many Requests"
    HttpStatusMessages.Add 431, "Request Header Fields Too Large"
    HttpStatusMessages.Add 444, "Connection Closed Without Response"
    HttpStatusMessages.Add 451, "Unavailable For Legal Reasons"
    HttpStatusMessages.Add 499, "Client Closed Request"
    HttpStatusMessages.Add 500, "Internal Server Error"
    HttpStatusMessages.Add 501, "Not Implemented"
    HttpStatusMessages.Add 502, "Bad Gateway"
    HttpStatusMessages.Add 503, "Service Unavailable"
    HttpStatusMessages.Add 504, "Gateway Timeout"
    HttpStatusMessages.Add 505, "HTTP Version Not Supported"
    HttpStatusMessages.Add 506, "Variant Also Negotiates"
    HttpStatusMessages.Add 507, "Insufficient Storage"
    HttpStatusMessages.Add 508, "Loop Detected"
    HttpStatusMessages.Add 510, "Not Extended"
    HttpStatusMessages.Add 511, "Network Authentication Required"
    HttpStatusMessages.Add 599, "Network Connect Timeout Error"
End Sub
